site_name: Frogwatch Handleiding
site_description: Handleiding voor het Frogwatch Trillingsmeter platform
site_author: Jitter
site_url: https://frog.watch/handleiding

nav:
    - Home: index.md
    - About: about.md

theme:
  name: readthedocs
  custom_dir: custom_theme/
extra_css: [extra.css]